---
title: Reflecting on "Things Learned from Anders" by Zwaan
author: ''
date: '2020-06-25'
slug: reflecting-on-things-learned-from-anders-by-zwaan
categories: []
tags: []
header:
  caption: ''
  image: ''
  preview: yes
draft: true
---

{{% tweet 817461069014859780 %}}

sdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf j

## Read and think broadly and deeply
sdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf j

## On when to conduct an experiment
sdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf j

## Go for the biggest effect
sdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf j

## Be curious about what the participants in your experiment are actually thinking
sdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf j

## Do work that will be cited 50 years from now
sdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf j

## Always raise the bar, not just for others but also for yourself
sdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf jsdlfhasdkfj alsdkjf laksdjf laksjdf lkasjflkas jfl;kj aslkf j