---
title: A decade at Keele
author: ''
date: '2020-07-01'
slug: a-decade-at-keele
categories: [General]
tags: [General]
header:
  caption: ''
  image: ''
  preview: yes
---

Today marks my 10 year anniversary of working at Keele University. On the one hand it feels like a blink of an eye, and yet on the other a lifetime. (Well, as I am 38 years old, a quarter of a lifetime.) 

I started my lectureship in Psychology at Keele on the 1st July 2010, 3 weeks before I obtained my PhD. Imposter syndrome was---and still is---alive and well. Looking at the CV I appended to my job application, I had 2 papers published, 1 paper in press, and 1 under review. It's strange to think that such a CV wouldn't even make a long-list in today's job market for lectureships. Even though I didn't feel ready, I applied to Keele at the advice of my PhD supervisor: "If you get it, great; if not, you gain the experience of an application process". This was wonderful advice, and on the day of the interview I remember being much more relaxed than I thought possible; after all, I was just there for the experience, right? On the day there was another candidate with a much better publication record than me interviewing, so that cemented in my mind that there was no way I would get the post. I left Keele that day thinking that I had gained a lot from the experience, but that I would not be successful. 

So I was completely shocked when---a few days later---the Head of School called. I remember that moment vividly: It was March and I was in my PhD office at Bangor University working on a paper; my PhD didn't finish until September 1st, so my early thesis submission meant I had a few months of working on other things. The HoS informed me I had been successful. I fell silent, and he had to prompt me: "Well, would you like to accept the position?". Of course I did!

Starting Keele meant living away from my (now) wife mid-week. We lived in Bangor North Wales, and Keele was a 2 hour drive away. Whilst there would be days later in my Keele tenure when I would sleep at home and do daily 4-hour commutes, in the early days I rented a flat on Keele campus (later moving to the lap of luxury by staying in the local Travelodge). Relocation is a well-known challenge of academic life and it was certainly the hardest part of starting my first lectureship. There were many evenings where I sat in my flat wondering whether this upheaval was worth it. My wife and I viewed the temporary living arrangements as an investment in our future. We soon got into a routine: I would leave Wales very early Monday morning, and would travel home late Wednesday evening, so it was only two nights apart for most weeks.  

Much has filled the past 10 years. I've tried to immerse myself in all arms of the academic profile (research, teaching, and service). Each bring their own unique challenges, and I've enjoyed engaging with them all. 

I spend too much of my time comparing myself to others around me, especially when it comes to research productivity and success. This can be terribly demotivating, because there are many excellent scientists winning grants, winning awards, and publishing beautiful papers. So, if instead I compare myself **to myself 10-years ago**, I think I am pretty pleased with what I have achieved at Keele. I have maintained a decent research profile. (I haven't won any large grants, and this is something I need to work very hard on.) I have published a decent amount. I have published a book. I have developed my statistical skills, programming skills, and computational modelling skills. I have supervised over 100 undergraduate research projects, 10 MSc projects, and 2 PhD projects. I have designed and delivered many modules. I created and led an MSc programme. I have led a research group in the School. I have taught hundreds of students. I have won some teaching awards. I hope I have been a good colleague. For the past 3 years I have been the Head of School, which has been very challenging, but I am pleased I took it on. 

I am now entering the dreaded "mid-career" stage. I step down from Head of School in September, so this will be an opportune time to reflect more on the past 10 years and my future direction. 

Keele has been a wonderful place to spend the first 10 years of my academic career. I owe a debt of gratitude to all at Keele for giving me my start in my academic career. 